# fly.toml app configuration file generated for aged-fire-5580 on 2023-07-05T11:07:35-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-fire-5580"
primary_region = "scl"

[build]
  [build.args]
    NEXT_PUBLIC_EXAMPLE = "Value goes here"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
